### ISSUE TITLE
Container start fails because of missing S3_SERVICE variable

### ISSUE THREAD

**Issue by zc-devs** [nginxinc/nginx-s3-gateway#247]
### Describe the bug

Pod fails to run with error:
```
Required S3_SERVICE environment variable missing
```

while documentation says that there should be `s3` default value.

BTW, documentation formatting is broken and there is no description as well.

### To reproduce

1. Start container with config
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ngs3gw
data:
  S3_STYLE: path
  S3_BUCKET_NAME: main
  S3_SERVER: minio.minio.svc.cluster.local
  S3_SERVER_PROTO: http
  S3_SERVER_PORT: "9000"
  S3_REGION: eu
  DEBUG: "true"
  AWS_SIGS_VERSION: "4"
  ALLOW_DIRECTORY_LIST: "true"
```
2. View logs of Pod 
3. See error
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/00-check-for-required-env.sh
Required S3_SERVICE environment variable missing
```

### Expected behavior

Container/Pod starts.

### Your environment

- ghcr.io/nginxinc/nginx-s3-gateway/nginx-oss-s3-gateway:unprivileged-oss-20240507
- Target deployment platform: K3s
- S3 backend implementation: MinIO

### Additional context

Worked on `unprivileged-oss-20240113`. Works on `unprivileged-oss-20240507` if `S3_SERVICE: s3` is set.
