### ISSUE TITLE
Startup fails when using IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by jnodorp-jaconi** [nginxinc/nginx-s3-gateway#70]
nginx-s3-gateway container does not start when using IAM roles for service accounts (in EKS) as authentication mechanism.

**To Reproduce**
start the container with the following variables:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: example
  template:
    metadata:
      labels:
        app.kubernetes.io/name: example
    spec:
      serviceAccountName: my-sa
      containers:
        - name: nginx-s3-gateway
          image: nginxinc/nginx-s3-gateway:latest
          env:
            - name: AWS_SIGS_VERSION
              value: "4"
            - name: S3_BUCKET_NAME
              value: my-bucket
            - name: S3_REGION
              value: us-east-1
            - name: S3_SERVER
              value: s3.us-east-1.amazonaws.com
            - name: S3_SERVER_PORT
              value: "443"
            - name: S3_SERVER_PROTO
              value: "https"
            - name: S3_STYLE
              value: default
```

causes this error on startup:

```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/00-check-for-required-env.sh
Required S3_ACCESS_KEY_ID environment variable missing
Required S3_SECRET_KEY environment variable missing
```

**Expected behavior**
The container startup should not fail.

**Your environment**
* Version of the repo: latest (30529460188d4ffbd2ab8d298ce04407258c6ffb)
* Version of the container used: latest (42aa78b1f5d7c316ea93611ccae44170519b434e96070f17b388b07bf4cf4c67)
* S3 backend implementation: AWS
* How you are deploying: EKS
* NGINX type: OSS
* Authentication method: IAM role for service account
